// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	db "github.com/mwhite7112/woodpantry-ingredients/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateIngredient(ctx context.Context, arg db.CreateIngredientParams) (db.Ingredient, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredient")
	}

	var r0 db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngredientParams) (db.Ingredient, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngredientParams) db.Ingredient); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateIngredientParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredient'
type MockQuerier_CreateIngredient_Call struct {
	*mock.Call
}

// CreateIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateIngredientParams
func (_e *MockQuerier_Expecter) CreateIngredient(ctx interface{}, arg interface{}) *MockQuerier_CreateIngredient_Call {
	return &MockQuerier_CreateIngredient_Call{Call: _e.mock.On("CreateIngredient", ctx, arg)}
}

func (_c *MockQuerier_CreateIngredient_Call) Run(run func(ctx context.Context, arg db.CreateIngredientParams)) *MockQuerier_CreateIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_CreateIngredient_Call) Return(_a0 db.Ingredient, _a1 error) *MockQuerier_CreateIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateIngredient_Call) RunAndReturn(run func(context.Context, db.CreateIngredientParams) (db.Ingredient, error)) *MockQuerier_CreateIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubstitute provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateSubstitute(ctx context.Context, arg db.CreateSubstituteParams) (db.IngredientSubstitute, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubstitute")
	}

	var r0 db.IngredientSubstitute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateSubstituteParams) (db.IngredientSubstitute, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateSubstituteParams) db.IngredientSubstitute); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngredientSubstitute)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateSubstituteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateSubstitute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubstitute'
type MockQuerier_CreateSubstitute_Call struct {
	*mock.Call
}

// CreateSubstitute is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateSubstituteParams
func (_e *MockQuerier_Expecter) CreateSubstitute(ctx interface{}, arg interface{}) *MockQuerier_CreateSubstitute_Call {
	return &MockQuerier_CreateSubstitute_Call{Call: _e.mock.On("CreateSubstitute", ctx, arg)}
}

func (_c *MockQuerier_CreateSubstitute_Call) Run(run func(ctx context.Context, arg db.CreateSubstituteParams)) *MockQuerier_CreateSubstitute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateSubstituteParams))
	})
	return _c
}

func (_c *MockQuerier_CreateSubstitute_Call) Return(_a0 db.IngredientSubstitute, _a1 error) *MockQuerier_CreateSubstitute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateSubstitute_Call) RunAndReturn(run func(context.Context, db.CreateSubstituteParams) (db.IngredientSubstitute, error)) *MockQuerier_CreateSubstitute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUnitConversion provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUnitConversion(ctx context.Context, arg db.CreateUnitConversionParams) (db.UnitConversion, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUnitConversion")
	}

	var r0 db.UnitConversion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUnitConversionParams) (db.UnitConversion, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUnitConversionParams) db.UnitConversion); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.UnitConversion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUnitConversionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateUnitConversion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUnitConversion'
type MockQuerier_CreateUnitConversion_Call struct {
	*mock.Call
}

// CreateUnitConversion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUnitConversionParams
func (_e *MockQuerier_Expecter) CreateUnitConversion(ctx interface{}, arg interface{}) *MockQuerier_CreateUnitConversion_Call {
	return &MockQuerier_CreateUnitConversion_Call{Call: _e.mock.On("CreateUnitConversion", ctx, arg)}
}

func (_c *MockQuerier_CreateUnitConversion_Call) Run(run func(ctx context.Context, arg db.CreateUnitConversionParams)) *MockQuerier_CreateUnitConversion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUnitConversionParams))
	})
	return _c
}

func (_c *MockQuerier_CreateUnitConversion_Call) Return(_a0 db.UnitConversion, _a1 error) *MockQuerier_CreateUnitConversion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateUnitConversion_Call) RunAndReturn(run func(context.Context, db.CreateUnitConversionParams) (db.UnitConversion, error)) *MockQuerier_CreateUnitConversion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIngredient provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteIngredient(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngredient'
type MockQuerier_DeleteIngredient_Call struct {
	*mock.Call
}

// DeleteIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeleteIngredient(ctx interface{}, id interface{}) *MockQuerier_DeleteIngredient_Call {
	return &MockQuerier_DeleteIngredient_Call{Call: _e.mock.On("DeleteIngredient", ctx, id)}
}

func (_c *MockQuerier_DeleteIngredient_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeleteIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteIngredient_Call) Return(_a0 error) *MockQuerier_DeleteIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteIngredient_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeleteIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubstitutesByIngredient provides a mock function with given fields: ctx, ingredientID
func (_m *MockQuerier) DeleteSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) error {
	ret := _m.Called(ctx, ingredientID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubstitutesByIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, ingredientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteSubstitutesByIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubstitutesByIngredient'
type MockQuerier_DeleteSubstitutesByIngredient_Call struct {
	*mock.Call
}

// DeleteSubstitutesByIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientID uuid.UUID
func (_e *MockQuerier_Expecter) DeleteSubstitutesByIngredient(ctx interface{}, ingredientID interface{}) *MockQuerier_DeleteSubstitutesByIngredient_Call {
	return &MockQuerier_DeleteSubstitutesByIngredient_Call{Call: _e.mock.On("DeleteSubstitutesByIngredient", ctx, ingredientID)}
}

func (_c *MockQuerier_DeleteSubstitutesByIngredient_Call) Run(run func(ctx context.Context, ingredientID uuid.UUID)) *MockQuerier_DeleteSubstitutesByIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeleteSubstitutesByIngredient_Call) Return(_a0 error) *MockQuerier_DeleteSubstitutesByIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteSubstitutesByIngredient_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeleteSubstitutesByIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngredient provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetIngredient(ctx context.Context, id uuid.UUID) (db.Ingredient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredient")
	}

	var r0 db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Ingredient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Ingredient); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredient'
type MockQuerier_GetIngredient_Call struct {
	*mock.Call
}

// GetIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetIngredient(ctx interface{}, id interface{}) *MockQuerier_GetIngredient_Call {
	return &MockQuerier_GetIngredient_Call{Call: _e.mock.On("GetIngredient", ctx, id)}
}

func (_c *MockQuerier_GetIngredient_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetIngredient_Call) Return(_a0 db.Ingredient, _a1 error) *MockQuerier_GetIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetIngredient_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.Ingredient, error)) *MockQuerier_GetIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngredientByName provides a mock function with given fields: ctx, name
func (_m *MockQuerier) GetIngredientByName(ctx context.Context, name string) (db.Ingredient, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredientByName")
	}

	var r0 db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Ingredient, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Ingredient); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(db.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetIngredientByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredientByName'
type MockQuerier_GetIngredientByName_Call struct {
	*mock.Call
}

// GetIngredientByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuerier_Expecter) GetIngredientByName(ctx interface{}, name interface{}) *MockQuerier_GetIngredientByName_Call {
	return &MockQuerier_GetIngredientByName_Call{Call: _e.mock.On("GetIngredientByName", ctx, name)}
}

func (_c *MockQuerier_GetIngredientByName_Call) Run(run func(ctx context.Context, name string)) *MockQuerier_GetIngredientByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuerier_GetIngredientByName_Call) Return(_a0 db.Ingredient, _a1 error) *MockQuerier_GetIngredientByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetIngredientByName_Call) RunAndReturn(run func(context.Context, string) (db.Ingredient, error)) *MockQuerier_GetIngredientByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListIngredients provides a mock function with given fields: ctx
func (_m *MockQuerier) ListIngredients(ctx context.Context) ([]db.Ingredient, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListIngredients")
	}

	var r0 []db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Ingredient, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Ingredient); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListIngredients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIngredients'
type MockQuerier_ListIngredients_Call struct {
	*mock.Call
}

// ListIngredients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListIngredients(ctx interface{}) *MockQuerier_ListIngredients_Call {
	return &MockQuerier_ListIngredients_Call{Call: _e.mock.On("ListIngredients", ctx)}
}

func (_c *MockQuerier_ListIngredients_Call) Run(run func(ctx context.Context)) *MockQuerier_ListIngredients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_ListIngredients_Call) Return(_a0 []db.Ingredient, _a1 error) *MockQuerier_ListIngredients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListIngredients_Call) RunAndReturn(run func(context.Context) ([]db.Ingredient, error)) *MockQuerier_ListIngredients_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubstitutesByIngredient provides a mock function with given fields: ctx, ingredientID
func (_m *MockQuerier) ListSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]db.IngredientSubstitute, error) {
	ret := _m.Called(ctx, ingredientID)

	if len(ret) == 0 {
		panic("no return value specified for ListSubstitutesByIngredient")
	}

	var r0 []db.IngredientSubstitute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.IngredientSubstitute, error)); ok {
		return rf(ctx, ingredientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.IngredientSubstitute); ok {
		r0 = rf(ctx, ingredientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.IngredientSubstitute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ingredientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListSubstitutesByIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubstitutesByIngredient'
type MockQuerier_ListSubstitutesByIngredient_Call struct {
	*mock.Call
}

// ListSubstitutesByIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientID uuid.UUID
func (_e *MockQuerier_Expecter) ListSubstitutesByIngredient(ctx interface{}, ingredientID interface{}) *MockQuerier_ListSubstitutesByIngredient_Call {
	return &MockQuerier_ListSubstitutesByIngredient_Call{Call: _e.mock.On("ListSubstitutesByIngredient", ctx, ingredientID)}
}

func (_c *MockQuerier_ListSubstitutesByIngredient_Call) Run(run func(ctx context.Context, ingredientID uuid.UUID)) *MockQuerier_ListSubstitutesByIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListSubstitutesByIngredient_Call) Return(_a0 []db.IngredientSubstitute, _a1 error) *MockQuerier_ListSubstitutesByIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListSubstitutesByIngredient_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.IngredientSubstitute, error)) *MockQuerier_ListSubstitutesByIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnitConversionsByIngredient provides a mock function with given fields: ctx, ingredientID
func (_m *MockQuerier) ListUnitConversionsByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]db.UnitConversion, error) {
	ret := _m.Called(ctx, ingredientID)

	if len(ret) == 0 {
		panic("no return value specified for ListUnitConversionsByIngredient")
	}

	var r0 []db.UnitConversion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.UnitConversion, error)); ok {
		return rf(ctx, ingredientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.UnitConversion); ok {
		r0 = rf(ctx, ingredientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.UnitConversion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ingredientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListUnitConversionsByIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnitConversionsByIngredient'
type MockQuerier_ListUnitConversionsByIngredient_Call struct {
	*mock.Call
}

// ListUnitConversionsByIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientID uuid.UUID
func (_e *MockQuerier_Expecter) ListUnitConversionsByIngredient(ctx interface{}, ingredientID interface{}) *MockQuerier_ListUnitConversionsByIngredient_Call {
	return &MockQuerier_ListUnitConversionsByIngredient_Call{Call: _e.mock.On("ListUnitConversionsByIngredient", ctx, ingredientID)}
}

func (_c *MockQuerier_ListUnitConversionsByIngredient_Call) Run(run func(ctx context.Context, ingredientID uuid.UUID)) *MockQuerier_ListUnitConversionsByIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListUnitConversionsByIngredient_Call) Return(_a0 []db.UnitConversion, _a1 error) *MockQuerier_ListUnitConversionsByIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListUnitConversionsByIngredient_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.UnitConversion, error)) *MockQuerier_ListUnitConversionsByIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceSubstituteIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ReplaceSubstituteIngredient(ctx context.Context, arg db.ReplaceSubstituteIngredientParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceSubstituteIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ReplaceSubstituteIngredientParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_ReplaceSubstituteIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceSubstituteIngredient'
type MockQuerier_ReplaceSubstituteIngredient_Call struct {
	*mock.Call
}

// ReplaceSubstituteIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ReplaceSubstituteIngredientParams
func (_e *MockQuerier_Expecter) ReplaceSubstituteIngredient(ctx interface{}, arg interface{}) *MockQuerier_ReplaceSubstituteIngredient_Call {
	return &MockQuerier_ReplaceSubstituteIngredient_Call{Call: _e.mock.On("ReplaceSubstituteIngredient", ctx, arg)}
}

func (_c *MockQuerier_ReplaceSubstituteIngredient_Call) Run(run func(ctx context.Context, arg db.ReplaceSubstituteIngredientParams)) *MockQuerier_ReplaceSubstituteIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ReplaceSubstituteIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_ReplaceSubstituteIngredient_Call) Return(_a0 error) *MockQuerier_ReplaceSubstituteIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_ReplaceSubstituteIngredient_Call) RunAndReturn(run func(context.Context, db.ReplaceSubstituteIngredientParams) error) *MockQuerier_ReplaceSubstituteIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceSubstituteSubId provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ReplaceSubstituteSubId(ctx context.Context, arg db.ReplaceSubstituteSubIdParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceSubstituteSubId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ReplaceSubstituteSubIdParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_ReplaceSubstituteSubId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceSubstituteSubId'
type MockQuerier_ReplaceSubstituteSubId_Call struct {
	*mock.Call
}

// ReplaceSubstituteSubId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ReplaceSubstituteSubIdParams
func (_e *MockQuerier_Expecter) ReplaceSubstituteSubId(ctx interface{}, arg interface{}) *MockQuerier_ReplaceSubstituteSubId_Call {
	return &MockQuerier_ReplaceSubstituteSubId_Call{Call: _e.mock.On("ReplaceSubstituteSubId", ctx, arg)}
}

func (_c *MockQuerier_ReplaceSubstituteSubId_Call) Run(run func(ctx context.Context, arg db.ReplaceSubstituteSubIdParams)) *MockQuerier_ReplaceSubstituteSubId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ReplaceSubstituteSubIdParams))
	})
	return _c
}

func (_c *MockQuerier_ReplaceSubstituteSubId_Call) Return(_a0 error) *MockQuerier_ReplaceSubstituteSubId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_ReplaceSubstituteSubId_Call) RunAndReturn(run func(context.Context, db.ReplaceSubstituteSubIdParams) error) *MockQuerier_ReplaceSubstituteSubId_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceUnitConversionIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ReplaceUnitConversionIngredient(ctx context.Context, arg db.ReplaceUnitConversionIngredientParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceUnitConversionIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ReplaceUnitConversionIngredientParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_ReplaceUnitConversionIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceUnitConversionIngredient'
type MockQuerier_ReplaceUnitConversionIngredient_Call struct {
	*mock.Call
}

// ReplaceUnitConversionIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ReplaceUnitConversionIngredientParams
func (_e *MockQuerier_Expecter) ReplaceUnitConversionIngredient(ctx interface{}, arg interface{}) *MockQuerier_ReplaceUnitConversionIngredient_Call {
	return &MockQuerier_ReplaceUnitConversionIngredient_Call{Call: _e.mock.On("ReplaceUnitConversionIngredient", ctx, arg)}
}

func (_c *MockQuerier_ReplaceUnitConversionIngredient_Call) Run(run func(ctx context.Context, arg db.ReplaceUnitConversionIngredientParams)) *MockQuerier_ReplaceUnitConversionIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ReplaceUnitConversionIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_ReplaceUnitConversionIngredient_Call) Return(_a0 error) *MockQuerier_ReplaceUnitConversionIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_ReplaceUnitConversionIngredient_Call) RunAndReturn(run func(context.Context, db.ReplaceUnitConversionIngredientParams) error) *MockQuerier_ReplaceUnitConversionIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateIngredient(ctx context.Context, arg db.UpdateIngredientParams) (db.Ingredient, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngredient")
	}

	var r0 db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngredientParams) (db.Ingredient, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngredientParams) db.Ingredient); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateIngredientParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngredient'
type MockQuerier_UpdateIngredient_Call struct {
	*mock.Call
}

// UpdateIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateIngredientParams
func (_e *MockQuerier_Expecter) UpdateIngredient(ctx interface{}, arg interface{}) *MockQuerier_UpdateIngredient_Call {
	return &MockQuerier_UpdateIngredient_Call{Call: _e.mock.On("UpdateIngredient", ctx, arg)}
}

func (_c *MockQuerier_UpdateIngredient_Call) Run(run func(ctx context.Context, arg db.UpdateIngredientParams)) *MockQuerier_UpdateIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateIngredient_Call) Return(_a0 db.Ingredient, _a1 error) *MockQuerier_UpdateIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateIngredient_Call) RunAndReturn(run func(context.Context, db.UpdateIngredientParams) (db.Ingredient, error)) *MockQuerier_UpdateIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertIngredient provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpsertIngredient(ctx context.Context, arg db.UpsertIngredientParams) (db.Ingredient, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIngredient")
	}

	var r0 db.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpsertIngredientParams) (db.Ingredient, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpsertIngredientParams) db.Ingredient); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpsertIngredientParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpsertIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertIngredient'
type MockQuerier_UpsertIngredient_Call struct {
	*mock.Call
}

// UpsertIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpsertIngredientParams
func (_e *MockQuerier_Expecter) UpsertIngredient(ctx interface{}, arg interface{}) *MockQuerier_UpsertIngredient_Call {
	return &MockQuerier_UpsertIngredient_Call{Call: _e.mock.On("UpsertIngredient", ctx, arg)}
}

func (_c *MockQuerier_UpsertIngredient_Call) Run(run func(ctx context.Context, arg db.UpsertIngredientParams)) *MockQuerier_UpsertIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpsertIngredientParams))
	})
	return _c
}

func (_c *MockQuerier_UpsertIngredient_Call) Return(_a0 db.Ingredient, _a1 error) *MockQuerier_UpsertIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpsertIngredient_Call) RunAndReturn(run func(context.Context, db.UpsertIngredientParams) (db.Ingredient, error)) *MockQuerier_UpsertIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
