// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (name, aliases, category, default_unit)
VALUES ($1, $2, $3, $4)
RETURNING id, name, aliases, category, default_unit, created_at
`

type CreateIngredientParams struct {
	Name        string
	Aliases     []string
	Category    sql.NullString
	DefaultUnit sql.NullString
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient,
		arg.Name,
		pq.Array(arg.Aliases),
		arg.Category,
		arg.DefaultUnit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Aliases),
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, id)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, aliases, category, default_unit, created_at FROM ingredients WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Aliases),
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
	)
	return i, err
}

const getIngredientByName = `-- name: GetIngredientByName :one
SELECT id, name, aliases, category, default_unit, created_at FROM ingredients WHERE name = $1
`

func (q *Queries) GetIngredientByName(ctx context.Context, name string) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredientByName, name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Aliases),
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, aliases, category, default_unit, created_at FROM ingredients ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			pq.Array(&i.Aliases),
			&i.Category,
			&i.DefaultUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET aliases = $2, category = $3, default_unit = $4
WHERE id = $1
RETURNING id, name, aliases, category, default_unit, created_at
`

type UpdateIngredientParams struct {
	ID          uuid.UUID
	Aliases     []string
	Category    sql.NullString
	DefaultUnit sql.NullString
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredient,
		arg.ID,
		pq.Array(arg.Aliases),
		arg.Category,
		arg.DefaultUnit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Aliases),
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
	)
	return i, err
}

const upsertIngredient = `-- name: UpsertIngredient :one
INSERT INTO ingredients (name, aliases, category, default_unit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, aliases, category, default_unit, created_at
`

type UpsertIngredientParams struct {
	Name        string
	Aliases     []string
	Category    sql.NullString
	DefaultUnit sql.NullString
}

func (q *Queries) UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, upsertIngredient,
		arg.Name,
		pq.Array(arg.Aliases),
		arg.Category,
		arg.DefaultUnit,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Aliases),
		&i.Category,
		&i.DefaultUnit,
		&i.CreatedAt,
	)
	return i, err
}
