// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID          uuid.UUID
	Name        string
	Aliases     []string
	Category    sql.NullString
	DefaultUnit sql.NullString
	CreatedAt   time.Time
}

type IngredientSubstitute struct {
	ID           uuid.UUID
	IngredientID uuid.UUID
	SubstituteID uuid.UUID
	Ratio        float64
	Notes        sql.NullString
}

type UnitConversion struct {
	ID           uuid.UUID
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Factor       float64
}
