// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateSubstitute(ctx context.Context, arg CreateSubstituteParams) (IngredientSubstitute, error)
	CreateUnitConversion(ctx context.Context, arg CreateUnitConversionParams) (UnitConversion, error)
	DeleteIngredient(ctx context.Context, id uuid.UUID) error
	DeleteSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) error
	GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error)
	GetIngredientByName(ctx context.Context, name string) (Ingredient, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]IngredientSubstitute, error)
	ListUnitConversionsByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]UnitConversion, error)
	ReplaceSubstituteIngredient(ctx context.Context, arg ReplaceSubstituteIngredientParams) error
	ReplaceSubstituteSubId(ctx context.Context, arg ReplaceSubstituteSubIdParams) error
	ReplaceUnitConversionIngredient(ctx context.Context, arg ReplaceUnitConversionIngredientParams) error
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpsertIngredient(ctx context.Context, arg UpsertIngredientParams) (Ingredient, error)
}

var _ Querier = (*Queries)(nil)
