// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: substitutes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubstitute = `-- name: CreateSubstitute :one
INSERT INTO ingredient_substitutes (ingredient_id, substitute_id, ratio, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, ingredient_id, substitute_id, ratio, notes
`

type CreateSubstituteParams struct {
	IngredientID uuid.UUID
	SubstituteID uuid.UUID
	Ratio        float64
	Notes        sql.NullString
}

func (q *Queries) CreateSubstitute(ctx context.Context, arg CreateSubstituteParams) (IngredientSubstitute, error) {
	row := q.db.QueryRowContext(ctx, createSubstitute,
		arg.IngredientID,
		arg.SubstituteID,
		arg.Ratio,
		arg.Notes,
	)
	var i IngredientSubstitute
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.SubstituteID,
		&i.Ratio,
		&i.Notes,
	)
	return i, err
}

const deleteSubstitutesByIngredient = `-- name: DeleteSubstitutesByIngredient :exec
DELETE FROM ingredient_substitutes WHERE ingredient_id = $1 OR substitute_id = $1
`

func (q *Queries) DeleteSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubstitutesByIngredient, ingredientID)
	return err
}

const listSubstitutesByIngredient = `-- name: ListSubstitutesByIngredient :many
SELECT id, ingredient_id, substitute_id, ratio, notes FROM ingredient_substitutes WHERE ingredient_id = $1
`

func (q *Queries) ListSubstitutesByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]IngredientSubstitute, error) {
	rows, err := q.db.QueryContext(ctx, listSubstitutesByIngredient, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientSubstitute
	for rows.Next() {
		var i IngredientSubstitute
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.SubstituteID,
			&i.Ratio,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSubstituteIngredient = `-- name: ReplaceSubstituteIngredient :exec
UPDATE ingredient_substitutes SET ingredient_id = $1 WHERE ingredient_id = $2
`

type ReplaceSubstituteIngredientParams struct {
	IngredientID   uuid.UUID
	IngredientID_2 uuid.UUID
}

func (q *Queries) ReplaceSubstituteIngredient(ctx context.Context, arg ReplaceSubstituteIngredientParams) error {
	_, err := q.db.ExecContext(ctx, replaceSubstituteIngredient, arg.IngredientID, arg.IngredientID_2)
	return err
}

const replaceSubstituteSubId = `-- name: ReplaceSubstituteSubId :exec
UPDATE ingredient_substitutes SET substitute_id = $1 WHERE substitute_id = $2
`

type ReplaceSubstituteSubIdParams struct {
	SubstituteID   uuid.UUID
	SubstituteID_2 uuid.UUID
}

func (q *Queries) ReplaceSubstituteSubId(ctx context.Context, arg ReplaceSubstituteSubIdParams) error {
	_, err := q.db.ExecContext(ctx, replaceSubstituteSubId, arg.SubstituteID, arg.SubstituteID_2)
	return err
}
