// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_conversions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUnitConversion = `-- name: CreateUnitConversion :one
INSERT INTO unit_conversions (ingredient_id, from_unit, to_unit, factor)
VALUES ($1, $2, $3, $4)
RETURNING id, ingredient_id, from_unit, to_unit, factor
`

type CreateUnitConversionParams struct {
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Factor       float64
}

func (q *Queries) CreateUnitConversion(ctx context.Context, arg CreateUnitConversionParams) (UnitConversion, error) {
	row := q.db.QueryRowContext(ctx, createUnitConversion,
		arg.IngredientID,
		arg.FromUnit,
		arg.ToUnit,
		arg.Factor,
	)
	var i UnitConversion
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.FromUnit,
		&i.ToUnit,
		&i.Factor,
	)
	return i, err
}

const listUnitConversionsByIngredient = `-- name: ListUnitConversionsByIngredient :many
SELECT id, ingredient_id, from_unit, to_unit, factor FROM unit_conversions WHERE ingredient_id = $1
`

func (q *Queries) ListUnitConversionsByIngredient(ctx context.Context, ingredientID uuid.UUID) ([]UnitConversion, error) {
	rows, err := q.db.QueryContext(ctx, listUnitConversionsByIngredient, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitConversion
	for rows.Next() {
		var i UnitConversion
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.FromUnit,
			&i.ToUnit,
			&i.Factor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceUnitConversionIngredient = `-- name: ReplaceUnitConversionIngredient :exec
UPDATE unit_conversions SET ingredient_id = $1 WHERE ingredient_id = $2
`

type ReplaceUnitConversionIngredientParams struct {
	IngredientID   uuid.UUID
	IngredientID_2 uuid.UUID
}

func (q *Queries) ReplaceUnitConversionIngredient(ctx context.Context, arg ReplaceUnitConversionIngredientParams) error {
	_, err := q.db.ExecContext(ctx, replaceUnitConversionIngredient, arg.IngredientID, arg.IngredientID_2)
	return err
}
